export type Doodle = {
  id: number,
  oid: string,
  name: string,
  doodle_type: string,
  url: string,
  proxy_url: string,
  title: string,
  width: number,
  height: number,
  date_year: number,
  date_month: number,
  date_day: number,
  is_global: boolean,
  is_dynamic: boolean,
  is_highlighted: boolean,
  is_animated_gif: boolean,
  countries: string,
  blog_text: string,
  query: string,
  share_text: string,
  tags: string,
  standalone_html: string
}